version: '3.7'

services:

  postgres:
    container_name: account_service_postgres
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: account_service
      PGDATA: "/data/account_service/postgres"
    volumes:
      - postgres:/data/account_service/postgres
    ports:
      - "5436:5432"
    restart: unless-stopped

volumes:
  postgres:



