spring:
  application:
    name: account-service-client

    # ------------- DataBases
  datasource:
    url: jdbc:postgresql://localhost:5436/account_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        ddl-auto: validate
#        dialect: org.hibernate.dialect.PostgreSQLDialect  # PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
        show-sql: true
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  output:
    ansi:
      enabled: always

  liquibase:
    change-log: classpath:/db/changelog/master.yaml

logging:
  level:
    root: info
  #    org:
  #      springframework:
  #        security: debug

  file:
    name: logs/spring.log

server:
  port: 8071

queue:
  name: hello
  request:
    name: get-amount-request-queue
  response:
    name: get-amount-response-queue

app:
  desired_account_number: 100

client:
  rCount: 35
  wCount: 15
  #  idList: [1, 2, 3, 4, 5]
  simulationTime: 2
  idListLength: 50

